name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout LiveSplit
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch history
        run: git fetch --prune --unshallow --no-recurse-submodules

      - name: Checkout head_ref
        if: ${{ github.head_ref != '' }}
        run: git checkout -b ${{ github.head_ref }} || git checkout ${{ github.head_ref }}

      - name: Set up .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build LiveSplit
        run: >
          dotnet build
          -v m
          -c Release
          -p:DebugType=None
          .\LiveSplit.sln

      - name: Run tests
        run: >
          dotnet test
          -v m
          -c Release
          --no-restore --no-build
          .\LiveSplit.sln

      - name: Zip Transparent LiveSplit Build
        run: 7z a Transparent_LiveSplit_Build.zip .\bin\Release\*

      - name: Delete existing tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new tag and release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Transparent LiveSplit
          body: |
            Automated release for Transparent LiveSplit.
          draft: false
          prerelease: false
          files: Transparent_LiveSplit_Build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
